import Link from 'next/link'
import Navbar from './component/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='p-[10px]'>
          <Navbar />
          <main className='mt-[20px]'>{children}</main>
          <div className='mt-[1300px]'>
            <div className="bg-indigo-500 px-4 py-2 text-white"><Link href="/contact">Contact</Link></div>
          </div>
        </div>
      </body>
    </html>
  )
}
